# Generated by Django 5.1.1 on 2024-09-22 07:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contract')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('barber_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.barbertype', verbose_name='barber type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission Percentage')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Fixed Amount')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='saloon.barber', verbose_name='Barber')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('balance_profit', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Profit Balance')),
                ('balance_cash', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Cash Balance')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='saloon.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('current_tariff', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Current Tariff')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hairstyles/', verbose_name='Image')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='HairstyleTariffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Tariff')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to='saloon.hairstyle', verbose_name='Hairstyle')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount in default currency')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Current stock')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='saloon.currency', verbose_name='Currency')),
                ('item_purpose', models.ManyToManyField(related_name='items', to='saloon.hairstyle', verbose_name='Item purpose')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount in default currency')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('date_payment', models.DateField(default=django.utils.timezone.now, verbose_name='Payment date')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='saloon.barber', verbose_name='Barber')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='saloon.cashregister', verbose_name='Cash Register')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.currency', verbose_name='Currency')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.paymenttype', verbose_name='Payment type')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('purchase_price_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price in default currency')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase date')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Supplier')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='saloon.cashregister', verbose_name='Cash Register')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.currency', verbose_name='Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='saloon.item', verbose_name='Item')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='currency',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='barbertype',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_types', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='barber',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.CreateModel(
            name='Shave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount in default currency')),
                ('date_shave', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Shave date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaves', to='saloon.barber', verbose_name='Barber')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaves', to='saloon.cashregister', verbose_name='Cash Register')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaves', to='saloon.client', verbose_name='Client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaves', to='saloon.currency', verbose_name='Currency')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shaves', to='saloon.hairstyle', verbose_name='Hairstyle')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaves', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'salon')},
        ),
        migrations.AlterUniqueTogether(
            name='hairstyle',
            unique_together={('name', 'salon')},
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'salon')},
        ),
        migrations.AlterUniqueTogether(
            name='barbertype',
            unique_together={('name', 'salon')},
        ),
        migrations.CreateModel(
            name='ItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.barber', verbose_name='Barber')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='saloon.item', verbose_name='Item')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='saloon.salon', verbose_name='Salon')),
                ('shave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='saloon.shave', verbose_name='Shave')),
            ],
            options={
                'unique_together': {('item', 'shave', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('trans_name', models.CharField(max_length=255, verbose_name='Description of Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount in default currency')),
                ('date_trans', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction date')),
                ('trans_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, verbose_name='Transaction type')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saloon.cashregister', verbose_name='Cash Register')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.currency', verbose_name='Currency')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'unique_together': {('trans_name', 'salon', 'date_trans')},
            },
        ),
    ]
