# Generated by Django 5.0.6 on 2024-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempurchase',
            name='total_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Total purchase price'),
        ),
    ]
