# Generated by Django 5.1.1 on 2024-09-29 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0003_itempurchase_total_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemused',
            name='used_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Used date'),
        ),
    ]
