# Generated by Django 5.1.1 on 2024-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0004_itemused_used_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='Image'),
        ),
    ]
